name: discover_road
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  # 图片
  cupertino_icons: ^1.0.2
  
  # 网络请求
  dio: ^4.0.6
  get: ^4.6.1
  
  # 自动生成Model
  json_annotation:
  
  # 英文大小写转换
  english_words: 
  
  # 上拉刷新下拉加载
  flutter_easyrefresh:
  
  # button组件
  fbutton_nullsafety: ^5.0.0

  # 数据持久化
  shared_preferences: ^2.0.13

  #豆瓣app
  flutter_cache_manager: ^3.3.0

  palette_generator: ^0.3.2

  # flutter_webview_plugin: 0.4.0

  # webview_flutter: ^3.0.0

  video_player: ^2.2.17

  # 用来模拟网络返回的数据，这些数据是真实的，这里模拟

  fluttertoast: ^8.0.8

  cached_network_image: ^3.2.0


  
dev_dependencies:
  json_model: ^1.0.0
  json_serializable: ^5.0.0
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/icons/
